name: Publish and Move Power BI Report

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:
    paths:
      - "uploaded_files/*.pbix"  # Trigger on changes to files in uploaded_files directory

permissions:
  contents: write  # Give the workflow write permissions for pushing commits

jobs:
  publish:
    runs-on: ubuntu-latest

    outputs:
      pbix_file_path: ${{ steps.detect_file.outputs.pbix_file_path }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install requests
          pip install python-dotenv

      - name: Detect .pbix File
        id: detect_file
        run: |
          PBIX_FILE=$(find uploaded_files -type f -name "*.pbix" | head -n 1)
          if [ -z "$PBIX_FILE" ]; then
            echo "No .pbix file found in the uploaded_files folder; exiting."
            exit 1
          else
            echo "PBIX_FILE_PATH=$PBIX_FILE" >> $GITHUB_ENV
            echo "::set-output name=pbix_file_path::$PBIX_FILE"
          fi

      - name: Set Environment Variables for Publish
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          TENANT_ID: ${{ secrets.TENANT_ID }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          WORKSPACE_ID: ${{ secrets.WORKSPACE_ID }}
        run: |
          echo "CLIENT_ID=${CLIENT_ID}" >> $GITHUB_ENV
          echo "CLIENT_SECRET=${CLIENT_SECRET}" >> $GITHUB_ENV
          echo "TENANT_ID=${TENANT_ID}" >> $GITHUB_ENV
          echo "USERNAME=${USERNAME}" >> $GITHUB_ENV
          echo "PASSWORD=${PASSWORD}" >> $GITHUB_ENV
          echo "WORKSPACE_ID=${WORKSPACE_ID}" >> $GITHUB_ENV

      - name: Debug Environment Variables
        run: |
          echo "CLIENT_ID: ${CLIENT_ID}"
          echo "CLIENT_SECRET: ${CLIENT_SECRET}"
          echo "TENANT_ID: ${TENANT_ID}"
          echo "USERNAME: ${USERNAME}"
          echo "PASSWORD: ${PASSWORD}"
          echo "WORKSPACE_ID: ${WORKSPACE_ID}"
          echo "PBIX_FILE_PATH: ${PBIX_FILE_PATH}"
        env:
          CLIENT_ID: ${{ env.CLIENT_ID }}
          CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
          TENANT_ID: ${{ env.TENANT_ID }}
          USERNAME: ${{ env.USERNAME }}
          PASSWORD: ${{ env.PASSWORD }}
          WORKSPACE_ID: ${{ env.WORKSPACE_ID }}
          PBIX_FILE_PATH: ${{ needs.publish.outputs.pbix_file_path }}

      - name: Publish to Power BI
        env:
          CLIENT_ID: ${{ env.CLIENT_ID }}
          CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
          TENANT_ID: ${{ env.TENANT_ID }}
          USERNAME: ${{ env.USERNAME }}
          PASSWORD: ${{ env.PASSWORD }}
          WORKSPACE_ID: ${{ env.WORKSPACE_ID }}
          PBIX_FILE_PATH: ${{ needs.publish.outputs.pbix_file_path }}
        run: |
          python automation_script.py  # Replace with the actual name of your script
